project:
  type: website

website:
  title: "AN1_website"
  repo-url: "https://github.com/NekoKaruni/AN1.git"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: "https://github.com/NekoKaruni/AN1.git"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true

editor: visual
